import Head from "next/head";
import styled from "styled-components";
import { useState } from "react";
import { useImmer } from "use-immer";
import { projects } from "@/lib/initialValues";

export default function Home() {
  const [stateProjects, setStateProjects] = useState(projects);
  const [immerProjects, updateImmerProjects] = useImmer(projects);

  const handleStateProjectPrice = () => {
    const newStateProjects = stateProjects.map((stateProject, index) => {
      if (index === 0) {
        return {
          ...stateProject,
          items: stateProject.items.map((item, index) => {
            if (index === 0) {
              return {
                ...item,
                price: 555, // Here is the actual change
              };
            } else {
              return item;
            }
          }),
        };
      } else {
        return stateProject;
      }
    });
    setStateProjects(newStateProjects);
  };

  const handleImmerProjectPrice = () => {
    const newImmerProjects = (draft) => {
      draft[0].items[0] = { ...draft[0].items[0], price: 555 }; // Immer change
    };
    updateImmerProjects(newImmerProjects);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <h1>useState vs useImmer</h1>
        <StyledDiv>
          <h2>useState Project Price: </h2>
          <p>{stateProjects[0].items[0].price}</p>
          <button type="button" onClick={handleStateProjectPrice}>
            Change State Price
          </button>
        </StyledDiv>
        <StyledDiv>
          <h2>useImmer Project Price: </h2>
          <p>{immerProjects[0].items[0].price}</p>
          <button type="button" onClick={handleImmerProjectPrice}>
            Change Immer Price
          </button>
        </StyledDiv>
      </StyledMain>
    </>
  );
}

const StyledMain = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
`;

const StyledDiv = styled.div`
  border: solid white;
  width: 80%;
  padding: 0.8rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;

  h2 {
    font-size: 1.2rem;
  }

  p {
    color: lightgoldenrodyellow;
    font-size: 1rem;
    font-weight: bold;
  }

  button {
    width: 30%;
  }
`;
